version: "3"

tasks:
  install:
    aliases: ["i"]
    cmds:
      - bun install

  run:
    aliases: ["r", "dev"]
    cmds:
      - echo "环境变量 ${VUE_APP_DEBUG}"
      - bun run dev # vue2 项目使用 Bun 运行
      # - yarn run dev
      # - pnpm run dev --trace-warnings
    env:
      NODE_ENV: development
      VUE_APP_DEBUG: "true"

  run:prod:
    aliases: ["rp"]
    cmds:
      - echo "环境变量 ${VUE_APP_DEBUG}"
      - bun run dev
    env:
      VUE_APP_DEBUG: "false"
